<a href="https://colab.research.google.com/github/AJ-Walker/DevIncept-Python/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import numpy
import numpy as np

In [ ]:
# Creating a 1D array using numpy
sports = np.array(['Football', 'Cricket', 'Baseball', 'Basketball', 'Volleyball', 'Badminton'])
print(sports)

# Indexing operations on 1D array
print(sports[2])
print(sports[5])

# Slicing operations on 1D array
print(sports[2:3])
print(sports[:3])
print(sports[3:])

['Football' 'Cricket' 'Baseball' 'Basketball' 'Volleyball' 'Badminton']
Baseball
Badminton
['Baseball']
['Football' 'Cricket' 'Baseball']
['Basketball' 'Volleyball' 'Badminton']


In [ ]:
# Creating a 2D array using numpy
num_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(num_arr)

# Indexing operations on 2D array
print(num_arr[0])
print(num_arr[1][3])
print(num_arr[0][3])

# Slicing operations on 2D array
print(num_arr[:1])
print(num_arr[1,2:])
print(num_arr[1,:3])
print(num_arr[0,2:])
print(num_arr[0,:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
9
4
[[1 2 3 4 5]]
[ 8  9 10]
[6 7 8]
[3 4 5]
[1 2 3]


In [ ]:
# Basic operations with arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr1 / arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
# Numpy Functions on 1D and 2D Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr1= np.array([1,2,3,4])

# Array Shapes
print(arr.shape)
print(arr1.shape)

# 1D array
arr3 = np.array([50,34,23,67,12,89,98])
print("The dimension of the given array :", arr3.ndim)
print("The shape of the of the given array :", arr3.shape)
print("Total number of elements :", arr3.size)

# 2D array
arr4 = np.array([[34,67,12,34,67],[6,2,7,1,8],[2,4,6,8,10]])
print("The dimension of the given array :", arr4.ndim)
print("The shape of the given array :", arr4.shape)
print("Total number of elements :", arr4.size)

# 1D array
arr5 = np.array([3, 2, 0, 1])
print(np.sort(arr5))
   
# 2D array
arr6 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr6))

# Mean, Median, Mode, Standard Deviation
arr7 = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
print('Mean :', np.mean(arr7))

# Median
print('Median :', np.median(arr7))

# Mode
from scipy import stats
print('Mode :', stats.mode(arr7))

# Standard Deviation
print('Standard Deviation :', np.std(arr7))

(2, 4)
(4,)
The dimension of the given array : 1
The shape of the of the given array : (7,)
Total number of elements : 7
The dimension of the given array : 2
The shape of the given array : (3, 5)
Total number of elements : 15
[0 1 2 3]
[[2 3 4]
 [0 1 5]]
Mean : 5.5
Median : 5.5
Mode : ModeResult(mode=array([1]), count=array([1]))
Standard Deviation : 2.8722813232690143
